# Generated by Django 3.0 on 2019-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.CharField(max_length=120)),
                ('Temp', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Air_Quality', models.IntegerField()),
                ('Water_Level', models.IntegerField()),
            ],
        ),
    ]
